sudo: required
language: cpp
services:
  - docker

matrix:
  include:
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1404
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604
    - os: linux
      env:
        - DOCKER_IMAGE=centos7
    - os: linux
      env:
        - DOCKER_IMAGE=fedora26
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1611
        - DPDK_DIR=dpdk-stable-16.11.6
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1702
        - DPDK_DIR=dpdk-17.02
      env:
        - DOCKER_IMAGE=ubuntu1604-dpdk1711
        - DPDK_DIR=dpdk-stable-17.11.2
    - os: linux
      env:
        - DOCKER_IMAGE=ubuntu1604-pfring
        - PF_RING=True

    
before_install:
  - git clone http://github.com/seladb/PcapPlusPlus.git
  - docker pull seladb/$DOCKER_IMAGE:latest
  - docker run -itd --name $DOCKER_IMAGE -v $(pwd)/PcapPlusPlus:/PcapPlusPlus seladb/$DOCKER_IMAGE

script:
  - if [[ ! -z $DPDK_DIR  ]]; then
        docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && ./configure-linux.sh --dpdk --dpdk-home /$DPDK_DIR";
    elif [[ ! -z $PF_RING  ]]; then
        docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && ./configure-linux.sh --pf-ring --pf-ring-home /PF_RING";
    else
        docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && ./configure-linux.sh --default";
    fi
  - docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus && make all"
  - docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus/Tests/Packet++Test && Bin/Packet++Test"
  - docker exec -i $DOCKER_IMAGE bash -c "cd PcapPlusPlus/Tests/Pcap++Test && Bin/Pcap++Test -n -k 0"
  - tar -zcvf pcapplusplus-$DOCKER_IMAGE.tar.gz PcapPlusPlus/Dist
  - curl --upload-file pcapplusplus-$DOCKER_IMAGE.tar.gz https://transfer.sh/pcapplusplus-$DOCKER_IMAGE.tar.gz

